# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "puppetlabs/centos-7.0-64-puppet"

  config.vm.network "private_network", ip: "192.168.33.18"

  config.vm.synced_folder "../shared/web", "/var/www/myproject"

  #Scripts
  config.vm.provision "shell", path: "scripts/install_modules.sh"

  #Puppet
  config.vm.hostname = 'puppet'

  config.vm.provision :puppet do |puppet|
   # puppet.manifests_path = "environments/development/manifests"
   # puppet.manifest_file = "site.pp"
    puppet.environment_path = "environments"
    puppet.environment      = "development"
    puppet.module_path      = "modules"
  end

end
